// COMBINED REGRESSION TEST RUNNER
// Auto-generated by audit-fix-suggestions.py --regression
//
// Runs all finding-specific regression tests.
// Each test fails on vulnerable code and passes on fixed code.
//
// Individual tests:
//   - test_vuln-01_regression.rs
//   - test_vuln-02_regression.rs
//   - test_vuln-03_regression.rs
//   - test_vuln-04_regression.rs
//   - test_vuln-05_regression.rs
//   - test_vuln-06_regression.rs
//   - test_vuln-07_regression.rs
//   - test_vuln-08_regression.rs
//   - test_vuln-09_regression.rs
//   - test_vuln-10_regression.rs
//
// Usage:
//   anchor test tests/regression/test_all_regressions.rs
//   cargo test --manifest-path tests/regression/Cargo.toml

    mod test_test_vuln-01_regression;
    mod test_test_vuln-02_regression;
    mod test_test_vuln-03_regression;
    mod test_test_vuln-04_regression;
    mod test_test_vuln-05_regression;
    mod test_test_vuln-06_regression;
    mod test_test_vuln-07_regression;
    mod test_test_vuln-08_regression;
    mod test_test_vuln-09_regression;
    mod test_test_vuln-10_regression;

// Run all regression tests:
// cargo test --manifest-path tests/regression/Cargo.toml

#[cfg(test)]
mod regression_suite {
    // This module aggregates all finding-specific regression tests above.
    // Run `anchor test` or `cargo test` to execute all.
}
